[package]
name = "bresenham-demo"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bresenham = { path = "..", default-features = false, features = [
    "line",
    "circle",
    "ellipse",
    "bezier",
    "aa",
    "fill",
] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = [
    "CanvasRenderingContext2d",
    "Document",
    "Element",
    "HtmlCanvasElement",
    "HtmlElement",
    "ImageData",
    "MouseEvent",
    "Window",
    "console",
] }
